name: Terraform CI

on:
  push:
    branches:
      - feature/bash-functions
  pull_request:
    branches:
      - main

jobs:
  terraform-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init -backend=false

      - name: Run Bash Terraform checks
        run: bash scripts/terraform-check.sh CloudQM

  powershell-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init -backend=false

      - name: Run PowerShell Terraform checks
        shell: pwsh
        run: ./scripts/terraform-check.ps1 -ProjectName CloudQM
